## Tic-Tac-Toe Simulation
In this assignment you have to construct a python class "TicTacToe" which simulates the game of Tic-Tac-Toe, this will further be used as an enviroment to solve for you in next week.

You may add arguments to given functions as per your need and also additional helper functions (whose name should start with "_", convention for private functions), but only the initially given functions can be called by any user. No additional imports are allowed. The game always starts with X's turn.

In [43]:
import numpy as np

In [44]:
class TicTacToe:
    def __init__(self, n : int = 3):
        self.n = n
        self.grid = np.full((n, n), 0)
        self.currMove = 1
        self.moveNum = 0

    def act(self, action : int) -> tuple:
        self.action = action
        self.xMove = action // self.n
        self.yMove = action % self.n
        maxMove = self.n ** 2
        if action < 0 or action >= maxMove or self.grid[self.xMove][self.yMove] != 0:
            print("Wrong Move, try again!")
            return self.grid, 0, False
        self.moveNum += 1
        self.grid[self.xMove][self.yMove] = self.currMove
        if self._checkWin() == True:
            if self.currMove == 1:
                return self.grid, 1, True
            return self.grid, -1, True
        if self.moveNum == maxMove:
            return self.grid, 0, True
        self._changeMove()
        return self.grid, 0, False


    def reset(self):
        self.grid = np.full((self.n, self.n), 0)
        self.currMove = 1
        return self.grid, 0, False

    # def _checkWin(self):
    #     found = 1
    #     for i in range(self.n):
    #         if self.grid[self.xMove][i] != self.currMove:
    #             found = 0
    #             break
    #     if found == 1:
    #         return True
    #     found = 1
    #     for i in range(self.n):
    #         if self.grid[i][self.yMove] != self.currMove:
    #             found = 0
    #             break
    #     if found == 1:
    #         return True

    #     if self.xMove == self.yMove:
    #         for i in range(self.n):
    #             if self.grid[i][i] != self.currMove:
    #                 return False
    #         return True
    #     if self.xMove + self.yMove == self.n - 1:
    #         for i in range(self.n):
    #             if self.grid[i][self.n-i-1] != self.currMove:
    #                 return False
    #         return True
    #     return False
    def _checkWin(self):
    # Check rows
        for row in self.grid:
            if np.all(row == self.currMove):
                return True

        # Check columns
        for col in self.grid.T:
            if np.all(col == self.currMove):
                return True

        # Check diagonals
        diag1 = np.diag(self.grid)
        diag2 = np.diag(np.fliplr(self.grid))
        if np.all(diag1 == self.currMove) or np.all(diag2 == self.currMove):
            return True

        return False



    def _changeMove(self):
        if self.currMove == 1:
            self.currMove = -1
        else:
            self.currMove = 1


In [45]:
game = TicTacToe(n = 3)
a,b,c = game.reset()
print(a)
while not c:
    move = int(input("Enter the next move: "))
    a,b,c = game.act(move)
    print(a)
if (b == 1):
    print(f'X won')
elif b == -1:
    print("O won")
else:
    print("Draw")

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1 -1  0]
 [ 0  0  0]
 [ 0  0  0]]
[[ 1 -1  0]
 [ 1  0  0]
 [ 0  0  0]]
[[ 1 -1 -1]
 [ 1  0  0]
 [ 0  0  0]]
[[ 1 -1 -1]
 [ 1  0  0]
 [ 1  0  0]]
X won
